FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# ⛳ Skopíruj priamo .csproj (je to lokálny priečinok, nie vnorený!)
COPY UmbracoNextJsDemo.Site.csproj ./
RUN dotnet restore "./UmbracoNextJsDemo.Site.csproj"

# Skopíruj zvyšok
COPY . .

RUN dotnet build "UmbracoNextJsDemo.Site.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish "UmbracoNextJsDemo.Site.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UmbracoNextJsDemo.Site.dll"]
